name: Tag and Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git tag --list | tail -n 1)
          if [ -z "$TAG" ]; then
            TAG="v0.0.0"
          fi
          echo "LATEST_TAG=${TAG}" >> $GITHUB_ENV

      - name: Increment patch version
        id: increment_patch
        run: |
          IFS='.' read -r -a VERSION <<< "${{ env.LATEST_TAG#v}}"
          PATCH=$((VERSION[2] + 1))
          NEW_TAG="v${VERSION[0]}.${VERSION[1]}.$PATCH"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}